// kendra/src/Components/Projects/Projects.tsx
import { Container, Grid, List, ListItem, ListItemText, Typography } from '@mui/material';
import support from '../../assets/support.svg';

import { useMediaQuery } from '@mui/material';
import {ImpRef} from '../../Constants/DataObjects'
const Projects = () => {
  const isMobile = useMediaQuery('(max-width:600px)');
  return (
    <Grid container spacing={2}>
      <Grid item xs={4} >
        {!isMobile ? <Container>
          <img src={support} alt="Success" style={{ maxWidth: '100%',height:"auto"}} />
        </Container>
        : null}
      </Grid>
      <Grid item xs={isMobile ? 12 : 8}>
        <List>
          {<ListItem>
            <ListItemText
              primary={
                <Typography
                  sx={{ display: 'inline' }}
                  variant={!isMobile ? "h4" :'body2' } component={!isMobile ? "h1" : "body"}
                  color="text.primary"
                >
                  Check Out <a href={ImpRef.nibandh_pages}> "nibandh"</a> - a comprehensive and evolving repository where we document concise, practical reference materials encountered during our tech learning and usage journey { }

                </Typography>
              }
            />
                      <ListItemText
              primary={
                <Typography
                  sx={{ display: 'inline' }}
                  variant={!isMobile ? "h4" :'body2' } component={!isMobile ? "h1" : "body"}
                  color="text.primary"
                >
                  Check Out <a href={ImpRef.vartalaap_site}> "vartalaap"</a> - my semi - technical show which I host over its own web platform.
                </Typography>
              }
            />
          </ListItem>}
        </List>
        <Typography 
            sx={{ display: 'inline', textDecoration: 'underline;' , fontStyle: 'italic'}}
            component="p"
            variant={!isMobile ? "h4" :'body2' }
            color="text.primary"
        
        ><strong><i>Note</i></strong> : "nibandh" is actively looking for contributors. Please reach out over <a href="mailto:shashankforworkshekhar@gmail.com">email</a> or check out the <a href={ImpRef.nibandh_repo}>git repo</a> if you are interested.</Typography><br />
      <Typography 
            sx={{ display: 'inline', textDecoration: 'underline;' , fontStyle: 'italic'}}
            component="p"
            variant={!isMobile ? "h4" :'body2' }
            color="text.primary"
        
        ><strong><i>Announcement</i></strong> :  <strong>"vartalaap"</strong>  previously part of <strong>"kendra"</strong> is now being hosted independently . Head over <a href={ImpRef.vartalaap_site}>to the site</a>  to enjoy the show
        </Typography>
      </Grid>
    </Grid>
  );
};

export default Projects;

// kendra/src/routes/projects/+page.svelte
<script>
    import {ImpRef} from '$lib/config.js'
</script>

<section class="project">
    <h1> <i class="fa-solid fa-lightbulb"></i>&nbsp; What I am working on currently </h1>
    <ul>
        <!-- <li><a  href={ImpRef.nibandh_pages}>Nibandh  </a>&mdash; 
            a comprehensive and evolving repository where we document concise, practical reference materials encountered during our tech learning and usage journey. 
            This project is more than just a collection of notes; 
            it's a growing guidebook, shaped by experiences and insights, 
            tailored to assist both beginners and experienced tech enthusiasts alike
        </li> -->
        &nbsp;
        <li> <a  href={ImpRef.vartalaap_site}>Vartalaap </a> &mdash;
        A semi-techincal podcast hosted independently on its own site I build, talking about software engineering, worklife balance 
        and navigating careers among other things.
        </li>
        &nbsp;
    </ul>
    <h1 style="text-align: left;"><i class="fa-solid fa-lightbulb"></i>  &nbsp; Announcements</h1>
    <ul>

        <!-- <li>
            Nibandh is looking for more contributors.If you like techincal writing and will like to contribute , please get it touch 
            by <a href="mailto:shashankforworkshekhar@gmail.com">email</a> or go to <a href={ImpRef.nibandh_repo}>Nibandh's git repo</a>
        </li> -->
        <li> 
            Code for <i>Vartalaap</i> (podcast site) and <i>Kendra</i> (porfolio site) is my project <a href="https://github.com/thatShashankGuy/parisar"><i>parisar</i> which is now open source</a>. 
        </li>
        <li> 
            I am open for collaborations on open/close source projects . Feel free to reach out via 
            <a href="mailto:shashankforworkshekhar@gmail.com">email</a> or via <a href="/contact">direct message (DM)</a> section. 
        </li>
    </ul>
</section>
<style>
    section{
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: left;
        padding: 15%; 
    }
    h1{
        font-size: xx-large;
        text-align: left;
    }

    ul {
        list-style-type: disc; /* Use disc bullets for list items */
        font-size: xx-large; /* Adjust font size for desktop screens */
        margin: 0 auto; /* Center-align the content */
    }

    li {
        margin-bottom: 20px; /* Add spacing between list items */
    }

    @media (max-width: 768px) {
        ul {
            font-size: small; /* Adjust font size for smaller screens */
            padding-left: 10px; /* Reduce left padding on smaller screens */
        }
        section{
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: left;
        padding: 30% 12% 12% 12%;
        font-size: medium;
        height: 100%;
        }
        h1{
        font-size: medium;
    }

    }

 a {
        text-decoration:underline;
        color: #333;
        transition: color 0.3s ease;
        
    }

    a:hover {
        color: #333 
    }
</style>
